### ISSUE TITLE
[v3.1] Script seems to skip/crash ffmpeg almost immediately and fall over to handbrake.

### ISSUE THREAD

**Issue by Saltystew** [BrianDMG/conv2mp4-ps#23] opened 2017-10-21 22:18 UTC
![shot_171021_181601](https://user-images.githubusercontent.com/20447447/31856313-eb645e9e-b68b-11e7-85a6-2073d316589c.png)

So as you can see in the picture, it finds a file with DTS audio and plans to change it to AAC, except it finishes in one second or less. That's just not possible obviously. ffmpeg fails consistantly with any file I throw at it.

I force quit handbrake in this situation which is why the second error about the file being too small shows up.

**Comment by BrianDMG** [comment] 2017-10-22 00:37
If you run this in a PowerShell window, does ffmpeg output any errors?

**Comment by Saltystew** [comment] 2017-10-22 04:18
Yea it does give an error, line 59, it also didn't bother to check for a .mp4 file before deleting the .mkv file when this happened.

[testoutput.txt](https://github.com/BrianDMG/conv2mp4-ps/files/1404602/testoutput.txt)

**Comment by BrianDMG** [comment] 2017-10-22 04:25
I was able to reproduce this on my end by disabling keeping subtitles. Removing the "-c:s" flag solved the problem for me. Give 3.1.1 a shot and see if the issue persists.

**Comment by Saltystew** [comment] 2017-10-22 05:10
That seems to have worked, although odd because I had keeping subtitles as false anyway.

I still get some sort of error message, but the files convert and play fine.

Line 88.

[testoutput2.txt](https://github.com/BrianDMG/conv2mp4-ps/files/1404618/testoutput2.txt)

**Comment by BrianDMG** [comment] 2017-10-22 19:40
I'm not sure what that specifically refers to other than there was a read error at that specific position (it doesn't seem to be directly related to the script), but it seems to be a fairly common message. I'm going to go ahead and close this issue, but don't hesitate to let me know if it starts becoming a problem.

**Closed by BrianDMG** 2017-10-22 19:40 UTC
Labels: bug
