### ISSUE TITLE
Using 2.2v multiple instances of ffmpeg and handbrake start up and run, use lots of resources

### ISSUE THREAD

**Issue by Saltystew** [BrianDMG/conv2mp4-ps#11] opened 2017-04-26 00:02 UTC
So the script was definitely not doing this for me before 2.2 but now the script is re-encoding multiple files at once [because multiple instances](http://i.imgur.com/0StG51e.png) are going at one time. Completely destroys my computer if there are more than 2 video files to convert.

**Comment by Lowestkillcount** [comment] 2017-04-26 00:07
Is the lock file being created in the script directory?
If this fails then the script won't know it is already running. Should create an conv2mp4-ps.lock file in the same directory.

**Comment by Saltystew** [comment] 2017-04-26 00:39
Yea it did create it.

**Comment by BrianDMG** [comment] 2017-04-26 00:51
That's really odd, I'll see if I can recreate this.

**Comment by Saltystew** [comment] 2017-04-26 01:13
It actually got worse than what is shown in the picture, I just didn't screenshot it. Got so bad every single process you could see without scrolling was ffmpeg. It had found 32 files to convert.

**Comment by BrianDMG** [comment] 2017-04-26 01:14
Can you give me some details on how you're running the script? Are you running it manually, automatically? Any extenuating circumstances like manually exiting the script? If you're running it automatically, do you have task scheduler set to not run another instance if it's already running, as well?

**Comment by Saltystew** [comment] 2017-04-26 01:22
I run it automatically through task scheduler and its set to run indefinitely every hour.

No I don't ever manually exit the script or cancel any process. 

And yes I have it set to not run another instance if the task is already running.

**Comment by BrianDMG** [comment] 2017-04-26 01:59
@Lowestkillcount - are you having similar issues, or does it seem to be functioning correctly for you?

**Comment by Lowestkillcount** [comment] 2017-04-26 02:03
I'm running my bastardized version of 1.9 on my main stuff at the moment because i'm lazy and hadn't got around to upgrading yet. 

In saying that i just spent 30 mins trying to cause this issue in a dev environment and couldn't make it happen. It worked fine for me every time.

Only thing i can think of that i couldn't test is that the script isn't being run locally - @Saltystew - you aren't running from a UNC path are you?

**Comment by Saltystew** [comment] 2017-04-26 07:32
Nope, everything is running locally.

**Comment by BrianDMG** [comment] 2017-05-01 03:56
@Saltystew - Are you still having this issue?

**Comment by Saltystew** [comment] 2017-05-01 06:22
No but I stopped using 2.2 and went back to 2.1 after I reported this issue. I use the system for a lot of things and a lot of people use my plex server, I can't have it locking up for hours on end.

**Comment by BrianDMG** [comment] 2017-05-01 23:29
So I came across something last night that might have been the cause of your issue. 

If your log has the following output anywhere (especially at the end of the session):
`ERROR: conv2mp4-ps.lock could not be deleted. Full error below.
Cannot find path 'C:\WINDOWS\system32\conv2mp4-ps.lock' because it does not exist.`

It's because in the script, operations calling for the variable $lockFile should have been calling for $lock instead _($lockFile is simply the name of the lock file, whereas $lock is the full, absolute path to the lock file_). This caused the lock file to be created in the correct directory, but when the script looked for the file to delete, it was looking in  C:\Windows\system32 _(the location of Powershell.exe_) unless the script's file path was explicitly added to the "Start in" text box in Task Scheduler.

If any of that applies to your setup, it might explain why your script wasn't detecting that it was already running (_because the lock file didn't exist where the script was looking_). 

Just committed a fix for this with v2.2.1. Give it a shot and let me know if that doesn't resolve the issue for you.

**Comment by Saltystew** [comment] 2017-05-02 00:01
I actually do remember seeing that error, though I didn't think any thing of it at the time because nothing crazy (multiple instances) had happened yet.

I'll try the new update, thanks.

**Comment by BrianDMG** [comment] 2017-05-04 13:03
Is v2.2.1 working out for you?

**Comment by Saltystew** [comment] 2017-05-04 23:00
Yea it seems to be fixed, thank you.

**Comment by BrianDMG** [comment] 2017-05-04 23:10
Good deal. Closing this one out.

**Closed by BrianDMG** 2017-05-04 23:10 UTC
