### ISSUE TITLE
"Past duration 0.999992 too large" repeated many times

### ISSUE THREAD

**Issue by dalcon007** [BrianDMG/conv2mp4-ps#12] opened 2017-05-01 02:45 UTC
Just discovered your great tool - thanks for your hard work in putting this together.

I'm running v3.0 Snapshot 04122017. It's been working well, but today the following error showed up and repeated quite a few times. I was able to capture some of the output just before it stopped.

https://pastebin.com/WHyPdSwS

I believe ffmpeg displays this to inform about "possible rate control distortion", but I'm not sure if it was caused by the script, the media file or ffmpeg.

**Comment by BrianDMG** [comment] 2017-05-01 03:54
Hey, thanks for testing out v3! The "Past duration ### too large" message is 100% ffmpeg, and it seems like it's fairly harmless. I found this stackoverflow post about it: http://stackoverflow.com/questions/30782771/what-does-past-duration-x-xxx-too-large-mean. 

The accepted answer from that article states:
"FFMpeg versions after Jan 15 2015 often display this warning. It has been added to warn about possible rate control distortion, otherwise it does not cause any harm."

Another answer states that the cause of this message is:
"This warning message appears when trying to encode a high frame rate source to a low frame rate output, which means frames need to be dropped."

Has this happened on multiple different files, or just one file of several? Also, did the output file (the new .mp4) look ok?

**Comment by dalcon007** [comment] 2017-05-01 04:12
Thanks for sharing the links. The output files looked fine. It seems to be occurring on multiple files of the same series. I'll keep an eye on it, but if it's harmless then I should be okay.

Let me know if you need any specific testing or info on v3!

**Comment by BrianDMG** [comment] 2017-05-01 23:07
Thanks for offering! The testing I need for v3 is primarily for the setup script, and mainly just trying to break it. The core script is more or less the same as v2.2, but reads values from the config file instead of the user inputting them directly. I tested it pretty extensively myself, but if there's one thing I've learned it's that you can't rely on yourself to try and break your own code _(or at least, other people seem to be more creative at breaking things than I am, ha)_. 

I also can't decide if the setup script is actually an improvement for ease of use, or whether it will just annoy advanced users and cause more problems for less advanced users. I'm very open to constructive criticism, so if you have any thoughts, I'm open to hearing them.

I'll go ahead and close this issue for now, but feel free to update as needed.

**Closed by BrianDMG** 2017-05-01 23:07 UTC
