### ISSUE TITLE
Multiple errors when running latest version of script.

### ISSUE THREAD

**Issue by ipv89** [BrianDMG/conv2mp4-ps#54] opened 2020-02-10 00:07 UTC
The below error's are presented when attempting to convert any files. 

`ConvertFile : Cannot process argument transformation on parameter 'KeepSubs'. Cannot convert 
value "System.String" to type "System.Management.Automation.SwitchParameter". Boolean parameters 
accept only Boolean values and numbers, such as $True, $False, 1 or 0.
At C:\Scripts\FFMPEG\conv2mp4-ps-master\conv2mp4-ps.ps1:104 char:54
+ ...          ConvertFile -ConvertType Audio -KeepSubs:$cfg.keep_subtitles
+                                                       ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertFile], ParameterBindingArgumentTransformat 
   ionException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,ConvertFile
 
cmd.exe : '-i' is not recognized as an internal or external command,
At C:\Scripts\FFMPEG\conv2mp4-ps-master\files\func\GetAudioStreams.ps1:11 char:33
+     [int[]] $audioStreamArray = cmd.exe /c "$ffprobe $ffprobeArgs"
+                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ('-i' is not rec...ternal command,:String) [], Remote 
   Exception
    + FullyQualifiedErrorId : NativeCommandError
 
operable program or batch file.
Cannot index into a null array.
At C:\Scripts\FFMPEG\conv2mp4-ps-master\files\func\GetAudioStreams.ps1:14 char:9
+     If ($audioStreamArray[$audioStreamArray.Length-1] -ne 2) {
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArra`

**Comment by BrianDMG** [comment] 2020-02-10 02:09
Can you paste the value you have in your config for keep_subtitles?

**Comment by ipv89** [comment] 2020-02-10 02:14
sure thing.

#Subtitle options
keep_subtitles= true

**Comment by BrianDMG** [comment] 2020-02-10 02:18
What version of Powershell are you using? ($PSVersionTable.PSVersion)

**Comment by ipv89** [comment] 2020-02-10 02:19
I am using;

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17134  228

**Comment by BrianDMG** [comment] 2020-02-10 02:41
On line 83 of conv2mp4-ps.ps1, can you add (as a single line) 
`Log "`n`nkeep_subtitles: $($cfg.keep_subtitles), type: $($cfg.keep_subtitles.gettype().Name)"` and rerun the script, then paste the output (from your log) here?

**Comment by ipv89** [comment] 2020-02-10 19:02
After looking at the config file closely I noticed that I must have converted it to a txt file at some point. After deleting the file then creating a new one from the config it is now working.

I am still receiving the error

cmd.exe : '-i' is not recognized as an internal or external command,
At C:\Scripts\FFMPEG\conv2mp4-ps-master\files\func\GetAudioStreams.ps1:11 char:33
+     [int[]] $audioStreamArray = cmd.exe /c "$ffprobe $ffprobeArgs"
+                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ('-i' is not rec...ternal command,:String) [], Remote 
   Exception
    + FullyQualifiedErrorId : NativeCommandError
 
operable program or batch file.
Cannot index into a null array.
At C:\Scripts\FFMPEG\conv2mp4-ps-master\files\func\GetAudioStreams.ps1:14 char:9
+     If ($audioStreamArray[$audioStreamArray.Length-1] -ne 2) {
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

The getaudiostreams file is unchanged

**Comment by BrianDMG** [comment] 2020-02-10 23:03
Found a bug after doing a little testing on my end, pushed a fix to the develop branch. Switch over to develop, run git pull, and let me know if the issue persists.

**Comment by BrianDMG** [comment] 2020-02-13 23:02
Assuming the issue is resolved. Feel free to reopen if that's not the case.

**Closed by BrianDMG** 2020-02-13 23:02 UTC
Labels: Bug
